### ISSUE TITLE
Create Cookies file with decrypted values that can be moved across computers

### ISSUE THREAD

**Issue by illera88** [illera88/GCC-stealer#11]
On `net\extras\sqlite\sqlite_persistent_cookie_store.cc` we find:

```c++
sql::Statement smt, delete_statement;
  if (restore_old_session_cookies_) {
    smt.Assign(db()->GetCachedStatement(
        SQL_FROM_HERE,
        "SELECT creation_utc, host_key, top_frame_site_key, name, value, path, "
        "expires_utc, is_secure, is_httponly, last_access_utc, has_expires, "
        "is_persistent, priority, encrypted_value, samesite, source_scheme, "
        "source_port, is_same_party, last_update_utc FROM cookies WHERE "
        "host_key = ?"));
  } else {
    smt.Assign(db()->GetCachedStatement(
        SQL_FROM_HERE,
        "SELECT creation_utc, host_key, top_frame_site_key, name, value, path, "
        "expires_utc, is_secure, is_httponly, last_access_utc, has_expires, "
        "is_persistent, priority, encrypted_value, samesite, source_scheme, "
        "source_port, is_same_party, last_update_utc FROM cookies WHERE "
        "host_key = ? AND "
        "is_persistent = 1"));
  }

[...]
bool SQLitePersistentCookieStore::Backend::MakeCookiesFromSQLStatement(
    std::vector<std::unique_ptr<CanonicalCookie>>& cookies,
    sql::Statement& statement,
    std::unordered_set<std::string>& top_frame_site_keys_to_delete) {
  DCHECK(background_task_runner()->RunsTasksInCurrentSequence());
  bool ok = true;
  while (statement.Step()) {
    std::string value;
    std::string encrypted_value = statement.ColumnString(13);
    if (!encrypted_value.empty() && crypto_) {
      bool decrypt_ok = crypto_->DecryptString(encrypted_value, &value);
      if (!decrypt_ok) {
        RecordCookieLoadProblem(COOKIE_LOAD_PROBLEM_DECRYPT_FAILED);
        ok = false;
        continue;
      }
    } else {
      value = statement.ColumnString(4);
    }
```

therefore if we fill the `value` column with the decrypted cookie value **AND** clear the `encrypted_value` column, Chrome should use the decrypted `value` column making the Cookies DB movable across different machines.

**Comment by Jigsaw855** [comment]
hi, I tested your tools and encountered the  error that you see in the image below , what is the cause?
![Screenshot (54)](https://github.com/illera88/GCC-stealer/assets/109898739/8a621ce5-0515-4172-8043-743b77d2df4c)

**Comment by illera88** [comment]
please open a new issue instead of using an existing one. 
Also, you should use  `--cookies-path` with the path of the `Cookies` file. Not to the dir where the `Cookies` file is. Newer versions of Chrome have the `Cookies` file on the `Network` path (example: `"C:\Users\MyUser\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies" `)

**Comment by jerry8219cool** [comment]
Hello please help me. I see error “CryptUnprotectData failed decrypting encrypted_key”
![Uploading IMG_7950.jpeg…]()

**Comment by illera88** [comment]
Hi @jerry8219cool ,

Open a new ticket and share as much info as possible to know what's happpening (OS, Browser version, ...)
