### ISSUE TITLE
DB file handle leak

### ISSUE THREAD

**Issue by mycyty** [illera88/GCC-stealer#15]
Why did you call the sqlite3_prepare_v2 function twice in succession? It will cause a file handle leak.

**Comment by illera88** [comment]
You are totally right. There is an extra line I created for debugging and I left it there. If you want to do a PR removing that line I'll merge it.

Line to delete
    ```auto a = sqlite3_prepare_v2(DB, sql, strlen(sql), &statement, 0);```
